name: cd

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
  
    # Environment variables
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Set up goose
        run: |
          #!/usr/bin/env bash
          go install github.com/pressly/goose/v3/cmd/goose@latest
          goose -version

      - name: Build the application
        run: ./scripts/buildprod.sh

      - name: Database migrations
        run: ./scripts/migrateup.sh

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'

      - name: 'Use gcloud CLI'
        run: 'gcloud info'

      - name: 'Build and Push to GAR'
        run: 'gcloud builds submit --tag europe-west1-docker.pkg.dev/notely-446817/notely-ar-repo/notely:latest'

      - name: 'Deploy to Cloud Run'
        run: 'gcloud run deploy notely --image europe-west1-docker.pkg.dev/notely-446817/notely-ar-repo/notely:latest --region europe-west1 --allow-unauthenticated --project notely-446817 --max-instances=4'
