name: ci

on:
  pull_request:
    branches: [main]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Test Go code
        run: go test -cover ./...

      - name: Install gosec
        run: go install github.com/securego/gosec/v2/cmd/gosec@latest

  style:
    name: Style
    runs-on: ubuntu-latest

    steps:
      - name: Check out code for style
        uses: actions/checkout@v4

      - name: Set up Go for style
        uses: actions/setup-go@v5
        with:
          go-version: "1.23.0"

      - name: Format Go code
        run: |
          go fmt ./... && test -z $(go fmt ./...)

      - name: Set up staticcheck
        run: go install honnef.co/go/tools/cmd/staticcheck@latest

      - name: Run staticcheck
        run: staticcheck ./...
